services:
  fastapiweb:
    container_name: wuw-fastapi
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code/app
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    environment:
      DEBUG: 1
    volumes:
      - .:/code/app
    ports:
      - 9443:8000

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # - letsencrypt:/etc/letsencrypt
    depends_on:
      - fastapiweb